### PR TITLE
[FIX] website_event_require_login: fix _render_template() call

### PR DESCRIPTION
**Pull request by leiremartinezdesantos**
Wrong call of render_template() .  _render_template() converted a private function in standard Odoo v14.

### CODE REVIEW

**Comment by Daniel-CA** [comment]
LGTM :+1:

**Review by anajuaristi — APPROVED** [review]

**Comment by anajuaristi** [comment]
This fix solves the traceback:
```
 File "/opt/odoo/v14/github/oca/event/website_event_require_login/controllers/main.py", line 14, in registration_new
    return request.env["ir.ui.view"].render_template(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/v14/core/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v14/core/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'ir.ui.view' object has no attribute 'render_template'
```

**Comment by yajo** [comment]
How to reproduce?

**Comment by anajuaristi** [comment]
Just install event + website_event_require_login and try to register someone. You will obtain the traceback.

**Review by Daniel-CA — APPROVED** [review]

**Review by yajo — APPROVED** [review]

**Comment by yajo** [comment]
The merge failure is fixed in https://github.com/OCA/maintainer-quality-tools/pull/695.
